### ISSUE TITLE
Build error on gcc 4.7: 'this' was not captured for this lambda function

### ISSUE THREAD

**Issue by silverwind** [uWebSockets/uWebSockets#240]
Lifted from https://github.com/silverwind/droppy/issues/264, it looks like uws fails to build on Debian Wheezy, gcc 4.7.2:

<details><summary>build log</summary>
````
gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/rainbow/.node-gyp/6.4.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/droppy/node_modules/uws/.node-gyp"
make: Entering directory `/usr/lib/node_modules/droppy/node_modules/uws/build'
  CXX(target) Release/obj.target/uws/src/Extensions.o
In file included from ../src/Extensions.cpp:1:0:
../src/Extensions.h: In constructor 'PerMessageDeflate::PerMessageDeflate(ExtensionsParser&, int, std::string&)':
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::next_in' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::avail_in' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::total_in' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::next_out' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::avail_out' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::total_out' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::msg' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::state' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::zalloc' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::zfree' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::opaque' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::data_type' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::adler' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::reserved' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::next_in' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::avail_in' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::total_in' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::next_out' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::avail_out' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::total_out' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::msg' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::state' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::zalloc' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::zfree' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::opaque' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::data_type' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::adler' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::reserved' [-Wmissing-field-initializers]
  CXX(target) Release/obj.target/uws/src/HTTPSocket.o
../src/HTTPSocket.cpp: In static member function 'static void uWS::HTTPSocket::onReadable(uv_poll_t*, int, int)':
../src/HTTPSocket.cpp:121:93: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  CXX(target) Release/obj.target/uws/src/Network.o
  CXX(target) Release/obj.target/uws/src/Server.o
In file included from ../src/Server.cpp:5:0:
../src/Extensions.h: In constructor 'PerMessageDeflate::PerMessageDeflate(ExtensionsParser&, int, std::string&)':
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::next_in' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::avail_in' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::total_in' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::next_out' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::avail_out' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::total_out' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::msg' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::state' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::zalloc' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::zfree' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::opaque' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::data_type' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::adler' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::reserved' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::next_in' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::avail_in' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::total_in' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::next_out' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::avail_out' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::total_out' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::msg' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::state' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::zalloc' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::zfree' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::opaque' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::data_type' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::adler' [-Wmissing-field-initializers]
../src/Extensions.h:36:127: warning: missing initializer for member 'z_stream_s::reserved' [-Wmissing-field-initializers]
../src/Server.cpp: In constructor 'uWS::Server::Server(uWS::EventSystem&, int, unsigned int, unsigned int, uWS::SSLContext)':
../src/Server.cpp:149:20: warning: missing initializer for member 'z_stream_s::next_in' [-Wmissing-field-initializers]
../src/Server.cpp:149:20: warning: missing initializer for member 'z_stream_s::avail_in' [-Wmissing-field-initializers]
../src/Server.cpp:149:20: warning: missing initializer for member 'z_stream_s::total_in' [-Wmissing-field-initializers]
../src/Server.cpp:149:20: warning: missing initializer for member 'z_stream_s::next_out' [-Wmissing-field-initializers]
../src/Server.cpp:149:20: warning: missing initializer for member 'z_stream_s::avail_out' [-Wmissing-field-initializers]
../src/Server.cpp:149:20: warning: missing initializer for member 'z_stream_s::total_out' [-Wmissing-field-initializers]
../src/Server.cpp:149:20: warning: missing initializer for member 'z_stream_s::msg' [-Wmissing-field-initializers]
../src/Server.cpp:149:20: warning: missing initializer for member 'z_stream_s::state' [-Wmissing-field-initializers]
../src/Server.cpp:149:20: warning: missing initializer for member 'z_stream_s::zalloc' [-Wmissing-field-initializers]
../src/Server.cpp:149:20: warning: missing initializer for member 'z_stream_s::zfree' [-Wmissing-field-initializers]
../src/Server.cpp:149:20: warning: missing initializer for member 'z_stream_s::opaque' [-Wmissing-field-initializers]
../src/Server.cpp:149:20: warning: missing initializer for member 'z_stream_s::data_type' [-Wmissing-field-initializers]
../src/Server.cpp:149:20: warning: missing initializer for member 'z_stream_s::adler' [-Wmissing-field-initializers]
../src/Server.cpp:149:20: warning: missing initializer for member 'z_stream_s::reserved' [-Wmissing-field-initializers]
../src/Server.cpp: In lambda function:
../src/Server.cpp:179:44: error: 'this' was not captured for this lambda function
../src/Server.cpp: In lambda function:
../src/Server.cpp:183:46: error: 'this' was not captured for this lambda function
make: *** [Release/obj.target/uws/src/Server.o] Error 1
make: Leaving directory `/usr/lib/node_modules/droppy/node_modules/uws/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.11.0-12-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/droppy/node_modules/uws
gyp ERR! node -v v6.4.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
````
</details>

I think it's related to [this gcc bug fixed in 4.8.0](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=51494). Any workaround possible, given that Wheezy will still be supported for quite some time?

**Comment by alexhultman** [comment]
You need GCC 4.8 at least, what kind of OS is this?

**Comment by SEAPUNK** [comment]
Wheezy is an "oldstable" distribution (Jessie "stable" distro having GCC 4.9.x), LTS ending on May 2018.

**Comment by silverwind** [comment]
Unfortunately there's still a considerable userbase on those "stable" distributions, which are Debian 7 (gcc 4.7) and RHEL/CentOS 6 (gcc 4.4). I tried to fix this issue but it apparently doesn't suffice to get it to compile on 4.7:

```
../src/WebSocket.cpp:24:34: error: 'UINT16_MAX' was not declared in this scope
```

After that was fixed, I got the following error which I'm unsure how to fix:

```
../src/Server.cpp:180:10: error: cannot convert 'uWS::Server::Server(uWS::EventSystem&, int, unsigned int, unsigned int, uWS::SSLContext)::<lambda(uv_async_t*)>' to 'uv_async_cb {aka void (*)(uv_async_s*)}' for argument '3' to 'int uv_async_init(uv_loop_t*, uv_async_t*, uv_async_cb)'
../src/Server.cpp:184:10: error: cannot convert 'uWS::Server::Server(uWS::EventSystem&, int, unsigned int, unsigned int, uWS::SSLContext)::<lambda(uv_async_t*)>' to 'uv_async_cb {aka void (*)(uv_async_s*)}' for argument '3' to 'int uv_async_init(uv_loop_t*, uv_async_t*, uv_async_cb)'
```

I think if gcc < 4.8 won't be supported, it should be mentioned in the Readme, as I think a lot more people will hit this issue.

**Comment by alexhultman** [comment]
Well it can be seen as a deployment issue instead. You need GCC 4.8 because simply C++11 was fully supported in that version. However, it is possible to build more portable binaries by statically linking with libstdc++, or shipping a copy of one working version. This is kind of low prio though, I expect the user to run pretty up-to-date systems (not debian).

**Comment by alexhultman** [comment]
Yep that is a good solution for now. node-pre-gyp is really just another build system, it's not going to solve the problem of not having fully portable binaries. I already ship pre-compiled binaries that work on most modern Linux systems. Problem with static compilation is the module download size blows up to maybe 20 - 50 mb and will only grow bigger with more versions of Node.js to support. NPM is really not intended for native modules, they are missing many important features of a real package manager.

**Comment by silverwind** [comment]
> I already ship pre-compiled binaries

Excuse my lack of knowledge, but how exactly do the current prebuilts work? E.g. what factors determine if a prebuilt binary is available for a particular system?

Here's uname from one such distro by the way:
```
$ docker run -it debian:wheezy /bin/bash
root@8be2919c4705:/# uname -a
Linux 8be2919c4705 4.4.19-moby #1 SMP Thu Sep 1 09:44:30 UTC 2016 x86_64 GNU/Linux
```

**Comment by alexhultman** [comment]
Newer versions of GCC/G++ require newer versions of libstdc++/libc. What you can do is "merge" the code of the shared libs with the uWS lib - that makes it run on any Linux without any dependency on any particular system version. However this greatly increases the size of the libs binary so it is not really doable in an NPM module (NPM is completely worthless as a native package manager). So it is a very tricky situation.

**Comment by silverwind** [comment]
When I think about prebuilt binaries, I think about binaries targeting specific libc/arch combinations, hosted on a web server which then can be downloaded on-demand. I think CI systems like Jenkins could make something like this pretty easy.

OTOH, I wouldn't really see a 50 MB download from npm as a big issue.

**Comment by alexhultman** [comment]
I will see what I can do to improve the deployment issues.
