### ISSUE TITLE
Can not make on macOS since support for HTTP was introduced

### ISSUE THREAD

**Issue by mafrost** [uWebSockets/uWebSockets#430]
Just pulled the latest build on macOS (c++, clang-800.0.42.1) and was not able to build it any longer. It fails with the following errors:

```
.../uwebSockets/src/HTTPSocket.h:139:24: error: allocation of incomplete type 'uWS::HttpResponse'
            return new HttpResponse(*this);
                       ^~~~~~~~~~~~
.../uwebSockets/src/HTTPSocket.h:108:8: note: forward declaration of 'uWS::HttpResponse'
struct HttpResponse;
       ^
.../uwebSockets/src/HTTPSocket.h:145:13: warning: deleting pointer to incomplete type 'uWS::HttpResponse' may cause undefined behavior [-Wdelete-incomplete]
            delete response;
            ^      ~~~~~~~~
.../uwebSockets/src/HTTPSocket.h:108:8: note: forward declaration of 'uWS::HttpResponse'
struct HttpResponse;
       ^
```

It seems to be because the HttpResponse is forward declared, and when it is, the compiler can't know how much space to allocate when calling new. Before the http branch was merged this built without issues.

**Comment by alexhultman** [comment]
Yeah I will have to restructure that part later. It compiles in GCC for now though.

**Comment by dendisuhubdy** [comment]
Thanks

**Comment by alexhultman** [comment]
This should be fixed now
